### ISSUE TITLE
Exporting enums under names

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/enum-xyz#2]
Currently, if you export like this:

```
// enums.js
export const { Summer, Autumn, Winter, Spring } = Enum.String
```

Importing would then require you to import

```
// other file
import { Summer, Autumn, Winter, Spring } from './enums.js'
```

If you have many enums, this could be tedious and you may want to scope them to a name like `Seasons` which you could then call each item on. Ideally, it would look something like this:

```
import { Seasons } from './enums.js'
Seasons.Summer // 'Summer'
```

This may take some design changes. Curious to spark a conversation here on approach.

**Comment by texastoland** [comment]
@chasefleming clarified he means when multiple enums are defined in the same file or else:

```js
import * as Seasons from './seasons.js'
```

He figured out on Discord:

```js
export const Seasons = { Summer, Autumn, Winter, Spring } = Symbols
```

~~Close and add to readme?~~ 🚫

**Comment by chasefleming** [comment]
@texastoland Tested a little more and I had some errors about "ReferenceError: Summer is not defined." The error went away if I invoked `Strings` as a function, so may be another point towards the function invocation re the discussion in [your PR](https://github.com/chasefleming/enum-xyz/pull/1). Although if it's standard then scoping would have to be done a different way. Let's keep that chat on that thread.

**Comment by texastoland** [comment]
No it doesn't work. The problem is assignment is an expression but declaration is a statement. The names `Season`, etc. haven't been declared (`let Seasons`) in my example. I made a [Typescript Playground](https://www.typescriptlang.org/play?#code/N4KABGD0lgHmATA9gUwM4DsDkAXMLYBLNHcMAGxTwE8wBeOesABhAF8RQJowB3JAE4BrNGUp5YAGjC0G8Bqw5coMeBkEz8REqIjiwALyYAKYHGm02TM7ABcLC-eZg2ASnacyPfsN0Uq5jLSRgymgZbWcE6OLC7uHEA) and tested in the browser too:

```js
{
  // x doesn't exist
  let y = x = 0
}
{
  // works
  let x, y = x = 0
}
{
  // x nor y exists
  let z = ({ x, y } = { x: 0, y: 0 })
}
{
  // works
  let x, y, z = ({ x, y } = { x: 0, y: 0 })
}
```

**Comment by texastoland** [comment]
I see your point now. You'd like something like:

```ts
export const Seasons = Symbols("Summer", "Autumn", "Winter", "Spring")
```

Alternatively there could be a `toObject` method:

```ts
const seasons = Symbols()
const { Summer, Autumn, Winter, Spring } = seasons
// memoized keys
export const Seasons = seasons.toObject()
```

My only question is what do _those do_ that _this doesn't_?

```ts
export const Seasons = Symbols()

// or TypeScript

export const Seasons = Symbols<
  "Summer" | "Autumn" | "Winter" | "Spring"
>()
```

At write-time they're the same. At run-time the only difference is whether it's `undefined` which doesn't seem useful for enums. I'm adding iteration (`for (season of Seasons)`) which should make them nearly equivalent.

**Comment by chasefleming** [comment]
@texastoland I think there is something to the `toObject()` method. The ability to call methods on an enum would solve this other [issue proposing more methods](https://github.com/chasefleming/enum-xyz/issues/3).

Having to do it in so many lines doesn't feel right yet though. Although the destructured nature that makes the current syntax of creating enums in the library doesn't lend itself to doing this easily. 

There is a potential for needing just a more flexible enum that would be more easily exportable, and could also support methods easily which is proposed [on this ticket](https://github.com/chasefleming/enum-xyz/issues/4). I'm a little torn because it deviates from the syntax a bit, but think an enum library should also have something that supports a more flexible enum (e.g. key is foo, but value is "bar"...or even heterogenous enums), so it could be a developer choice as to which to use. Maybe if you're using it in a single file, you'd go with the destructured approach. Or, if a developer just liked the destructured syntax we could also support the methods with the above syntax providing `toObject` you mentioned. Then it keeps the library more consistent in that all enums support the same methods. For that reason, I think it's important to provide a way to support methods on the current syntax.

Curious to hear your thoughts.

**Comment by texastoland** [comment]
Exactly what I started implementing a few days ago 👍🏼 The short version is you just make the proxy wrap:

```js
new Proxy(
  config.create
    ? Object.setPrototypeOf((...args) => create(config, ...args), config)
    : Object.create(config),
  { ... }
)
```

That makes it automatically callable as a function (without an `apply` handler), work with `for ... in` and `Object` methods as noted (fixing #3 for memoized enums _only_), and shockingly simpler to implement memoization (no more crazy `map.get() ?? map.set(map.get()).get()`). Setting the prototype is an implementation detail to bring back state so the following should work:

```js
export const Integers = memoOf(
  enumOf({
    count: 0,
    get: (_, { count }) => count++,
    create: (config, start = 0) => enumOf({ ...config, count: start }),
  })
)
```

The typing was particularly challenging but hopefully I finally have it sorted. In theory it'll recognize `count: 0` as state and provide autocomplete in `get` and any other custom proxy handler. My apologies for the upcoming diff because it's a near complete rewrite.
